eureka:
  instance:
    hostname: localhost
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

server:
  port: 9092
  ssl:
    enabled: true
    key-store-type: JKS
    client-auth: need
    trust-store: ../Gateway/src/main/resources/static/keystore/truststore.jks
    trust-store-password: ENC(8T0KdePO2gKL+wdThp0TgMaYFY3L6kmt8NlJgi0g3jU=)
    trust-store-type: JKS
    key-store: ../Gateway/src/main/resources/static/keystore/zull-keystore.jks
    key-store-password: ENC(zcvJ2MlV/WTGBR92jMu/gHGBP0PSlKWR)
    key-alias: zull-proxy

jasypt:
  encryptor:
    password: timejts

zuul:
  routes:
    PKI:
      path: /api/certificates/**
      sensitive-headers: Set-Cookie, Authorization
      serviceId: PKI
      strip-prefix: false
      ribbon:
        listOfServers: https://localhost:8443/*
    SIEMCentreAlarms:
      path: /api/alarm/**
      sensitive-headers: Set-Cookie, Authorization
      serviceId: SIEMCentre
      strip-prefix: false
      ribbon:
        listOfServers: https://localhost:8082/*
    SIEMCentreLogs:
      path: /api/log/**
      sensitive-headers: Set-Cookie, Authorization
      serviceId: SIEMCentre
      strip-prefix: false
      ribbon:
        listOfServers: https://localhost:8082/*

hystrix:
  command:
    PKI:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:
              160000000
ribbon:
  OkToRetryOnAllOperations: true
  ReadTimeout: 5000000
  ConnectTimeout: 5000000
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 3
  CustomSSLSocketFactoryClassName: com.netflix.http4.ssl.AcceptAllSocketFactory
  IsHostnameValidationRequired: false

auth0:
  audience: https://localhost:9092

spring:
  security:
    oauth0:
      resourceserver:
        jwt:
          issuer-uri: https://dev-6w-2hyw1.eu.auth0.com/
          