eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

server:
  port: 9092
  ssl:
    enabled: true
    #key-store: C:\Users\Nemanja\Documents\DefenceFirst\Gateway\src\main\resources\static\keystore\gateway.jks
      #..\Gateway\src\main\resources\static\keystore\gateway.jks
    #key-store-password: ENC(vyc3Q2RuViKakldYClFr85DOEMDJXUWI)
    #key-alias: gateway
    #key-store-type: JKS
    #trust-store: C:\Users\Nemanja\Documents\DefenceFirst\Gateway\src\main\resources\static\keystore\gateway.jks
      #..\Gateway\src\main\resources\static\keystore\gateway.jks
    #trust-store-password: ENC(vyc3Q2RuViKakldYClFr85DOEMDJXUWI)
    #trust-store-type: JKS


jasypt:
  encryptor:
    password: timejts

spring:
  cloud:
    gateway:
      routes:
      - id: PKI
        uri: lb://PKI
        predicates:
        - Path=/api/certificates/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - HEAD
              - PUT
   #httpclient:
    #    ssl:
    #      trustedX509Certificates:
    #      - ..\PKI\src\main\resources\static\keystore\pki.crt
    #      - ..\Client\ssl\server.crt 

#hystrix:
#  command:
#    PKI:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds:
#              160000000

#ribbon:
#  OkToRetryOnAllOperations: true
#  ReadTimeout: 5000000
#  ConnectTimeout: 5000000
#  MaxAutoRetries: 3
#  MaxAutoRetriesNextServer: 3
#  CustomSSLSocketFactoryClassName: com.netflix.http4.ssl.AcceptAllSocketFactory
#  IsHostnameValidationRequired: false

#keycloak:
#  auth-server-url: http://localhost:8180/auth
#  cors: true
#  realm: Defence First Realm
#  resource: Defence First Client
#  bearer-only: true
#  ssl-required: external
#  credentials:
#    secret: f838e554-6ed4-4935-af58-bf68ccd514a7