eureka:
  instance:
    hostname: localhost
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    fetchRegistry: true
    ribbon:
        listOfServers: https://localhost:8443

server:
  port: 8082
  ssl:
    enabled: true
    key-store-type: JKS
    client-auth: need
    trust-store: ../SIEMCentre/src/main/resources/static/keystore/centre-truststore.jks
    trust-store-password: ENC(a2Yi+uzmpm+MbRTjurmJLa2BGIH2pMgK)
    trust-store-type: JKS
    key-store: ../SIEMCentre/src/main/resources/static/keystore/centre.jks
    key-store-password: ENC(a2Yi+uzmpm+MbRTjurmJLa2BGIH2pMgK)
    key-alias: centre

spring:
  data:
    mongodb:
      username: PKIAdmin
      password: ENC(j2x2swriTsvGWpRzoXX+tqsyekxgDjkmZjKnEoq2QS4=)
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@localhost:27017/?authSource=pki&authMechanism=SCRAM-SHA-256&readPreference=primary&ssl=false
      database: pki

rules:
  drt:
    exceededNumOfRequestsTemplate: ../SIEMCentreRules/src/main/resources/rules/templates/excNumOfReq.drt
    suspiciousBehaviourTemplate: ../SIEMCentreRules/src/main/resources/rules/templates/suspBehaviour.drt
    severityTemplate: ../SIEMCentreRules/src/main/resources/rules/templates/severity.drt
    maliciousTemplate: ../SIEMCentreRules/src/main/resources/rules/templates/malicious.drt
    exceededNumOfRequestsDRLPath: ../SIEMCentreRules/src/main/resources/rules/ExceededNumberOfRequests
    suspiciousBehaviourDRLPath: ../SIEMCentreRules/src/main/resources/rules/SuspiciousBehaviour
    severityDRLPath: ../SIEMCentreRules/src/main/resources/rules/Severity
    maliciousDRLPath: ../SIEMCentreRules/src/main/resources/rules/Malicious

jasypt:
  encryptor:
    password: timejts
